version: '3.8'
services:
  db:
    container_name: pgdb
    image: postgres
    command: ["postgres", "-c", "listen_addresses=*"]
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  jupyter:
    container_name: notebook
    image: jupyter/minimal-notebook
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: >
      bash -c "pip install -r /home/jovyan/work/notebooks/requirements.txt && 
      jupyter notebook --notebook-dir=/home/jovyan/work/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
volumes:
  minio_data:
